spring:
  config:
    activate:
      on-profile: test-h2
  datasource:
    url: jdbc:h2:mem:test
    username: user
    password: pwduser
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
